spring:
  application:
    name: order-service
  flyway:
    enabled: false
  config:
    import:
      - optional:configserver:http://localhost:8888
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include : '*'
  info:
    env:
      enabled: true