spring:
  application:
    name: order-service
  flyway:
    enabled: false
  config:
    import:
      - optional:configserver:http://localhost:8888

  mail:
    host: smtp.example.com
    port: 587
    username: user
    password: pass
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

invoice:
  mail:
    to-debug: "client@example.com" # temporaire si tu n’as pas l’email client

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include : '*'
  info:
    env:
      enabled: true

logging:
  level:
    audit.invoice: INFO

company:
  name: "Kora Market"
  rc: "RCCM: BF-OUA-2025-A-12345"
  ifu: "IFU: 0000000001234"
  address: "Zone du Bois, Ouagadougou, BF"
  phone: "+226 70 00 00 00"
  email: "support@koramarket.com"
  #logo-url: "https://example.com/logo.png" # facultatif
  logo-url: file:///D:/AES/Doc/KoraMarketBack/Documentations/logo.png
  website: "https://www.koramarket.com" # facultatif


clients:
  product:
    base-url: http://localhost:8082
