spring:
  application:
    name: commande-service
  flyway:
    enabled: false
  config:
    import:
      - optional:configserver:http://localhost:8888
      - optional:classpath:db-common.yml  # Ajoutez 'optional:'

#server:
#  port: 8083
#  servlet:
#    context-path: /api/orders
#
#spring:
#  application:
#    name: order-service
#  datasource:
#    url: jdbc:postgresql://localhost:5432/koramarket?currentSchema=order_service
#    username: postgres
#    password: admin
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        default_schema: order_service